name: Integration

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/integrate.yml'
      - 'action.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches:    
      - main
    paths:
      - '.github/workflows/integrate.yml'
      - 'action.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
jobs:
  test_defaults:
    name: Test defaults
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare key pairs
        id: prepare
        run: |
          # Generate key pair
          mkdir ~/.ssh && chmod 0700 ~/.ssh
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -P ''

          # Authorizing keys
          cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
          chmod 0600 ~/.ssh/authorized_keys
          sudo systemctl status sshd || sudo systemctl start sshd
          ssh-keyscan -t ed25519 localhost,127.0.0.1 >> ~/.ssh/known_hosts

          # Create test directories
          mkdir -p ./test/{local,remote}
          for content in bla bli blu; do
            mkdir -p ./test/local/${content}
            echo "Test content in ${content}" > ./test/local/${content}/${content}.ext
          done

      - name: Call action
        id: call
        uses: ./
        with:
          remote: "sftp://$(whoami):dummy@localhost/$(pwd)/test/remote/"
          local_dir: ./test/local/
          timeout: 10
        env:
          VERBOSE: 2
        continue-on-error: true

      - name: Verify
        id: verify
        run: |
          diff --recursive ./test/local ./test/remote
        continue-on-error: true

      - name: Proper exit
        run: |
          if [ ${{ steps.prepare.outcome }} != 'success'\
                -o ${{ steps.call.outcome }} != 'success' \
                -o ${{ steps.verify.outcome }} != 'success' ]
          then
            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
          fi
